// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testx;

#nullable disable

namespace Testx.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409141651_ExchangeRatesModel")]
    partial class ExchangeRatesModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Testx.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Trophies")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoundationDate = new DateTime(1902, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Real Madryt",
                            Trophies = 100
                        },
                        new
                        {
                            Id = 2,
                            FoundationDate = new DateTime(1899, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FC Barcelona",
                            Trophies = 95
                        },
                        new
                        {
                            Id = 3,
                            FoundationDate = new DateTime(1920, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jagiellonia Białystok",
                            Trophies = 2
                        });
                });

            modelBuilder.Entity("Testx.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Trophies")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Polska",
                            Trophies = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hiszpania",
                            Trophies = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brazylia",
                            Trophies = 5
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anglia",
                            Trophies = 1
                        });
                });

            modelBuilder.Entity("Testx.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationalityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("NationalityId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            ClubId = 2,
                            FirstName = "Robert",
                            LastName = "Lewandowski",
                            NationalityId = 1,
                            Position = "Napastnik",
                            Price = 15.0m,
                            Weight = 81.0
                        },
                        new
                        {
                            Id = 2,
                            Age = 23,
                            ClubId = 1,
                            FirstName = "Vinicius",
                            LastName = "Junior",
                            NationalityId = 3,
                            Position = "Napastnik",
                            Price = 180.0m,
                            Weight = 73.0
                        },
                        new
                        {
                            Id = 3,
                            Age = 20,
                            ClubId = 1,
                            FirstName = "Jude",
                            LastName = "Bellingham",
                            NationalityId = 4,
                            Position = "Pomocnik",
                            Price = 180.0m,
                            Weight = 75.0
                        },
                        new
                        {
                            Id = 4,
                            Age = 21,
                            ClubId = 2,
                            FirstName = "Pedri",
                            LastName = "Gonzalez",
                            NationalityId = 2,
                            Position = "Pomocnik",
                            Price = 90.0m,
                            Weight = 60.0
                        },
                        new
                        {
                            Id = 5,
                            Age = 23,
                            ClubId = 1,
                            FirstName = "Rodrygo",
                            LastName = "Goes",
                            NationalityId = 3,
                            Position = "Napastnik",
                            Price = 100.0m,
                            Weight = 64.0
                        },
                        new
                        {
                            Id = 6,
                            Age = 34,
                            ClubId = 2,
                            FirstName = "Wojciech",
                            LastName = "Szczęsny",
                            NationalityId = 1,
                            Position = "Bramkarz",
                            Price = 10.0m,
                            Weight = 90.0
                        },
                        new
                        {
                            Id = 7,
                            Age = 16,
                            ClubId = 2,
                            FirstName = "Lamine",
                            LastName = "Yamal",
                            NationalityId = 2,
                            Position = "Napastnik",
                            Price = 60.0m,
                            Weight = 65.0
                        },
                        new
                        {
                            Id = 8,
                            Age = 32,
                            ClubId = 3,
                            FirstName = "Taras",
                            LastName = "Romanczuk",
                            NationalityId = 1,
                            Position = "Pomocnik",
                            Price = 2.0m,
                            Weight = 80.0
                        },
                        new
                        {
                            Id = 9,
                            Age = 33,
                            ClubId = 3,
                            FirstName = "Jesus",
                            LastName = "Imaz",
                            NationalityId = 2,
                            Position = "Napastnik",
                            Price = 1.5m,
                            Weight = 70.0
                        },
                        new
                        {
                            Id = 10,
                            Age = 17,
                            ClubId = 1,
                            FirstName = "Endrick",
                            LastName = "Felipe",
                            NationalityId = 3,
                            Position = "Napastnik",
                            Price = 45.0m,
                            Weight = 72.0
                        },
                        new
                        {
                            Id = 11,
                            Age = 19,
                            ClubId = 2,
                            FirstName = "Gavi",
                            LastName = "Paez",
                            NationalityId = 2,
                            Position = "Pomocnik",
                            Price = 90.0m,
                            Weight = 68.0
                        },
                        new
                        {
                            Id = 12,
                            Age = 23,
                            ClubId = 3,
                            FirstName = "Bartłomiej",
                            LastName = "Wdowik",
                            NationalityId = 1,
                            Position = "Obrońca",
                            Price = 3.0m,
                            Weight = 74.0
                        },
                        new
                        {
                            Id = 13,
                            Age = 20,
                            ClubId = 2,
                            FirstName = "Fermin",
                            LastName = "Lopez",
                            NationalityId = 2,
                            Position = "Pomocnik",
                            Price = 20.0m,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = 14,
                            Age = 26,
                            ClubId = 1,
                            FirstName = "Eder",
                            LastName = "Militao",
                            NationalityId = 3,
                            Position = "Obrońca",
                            Price = 70.0m,
                            Weight = 79.0
                        },
                        new
                        {
                            Id = 15,
                            Age = 30,
                            ClubId = 1,
                            FirstName = "Harry",
                            LastName = "Kane",
                            NationalityId = 4,
                            Position = "Napastnik",
                            Price = 110.0m,
                            Weight = 86.0
                        });
                });

            modelBuilder.Entity("Testx.Models.Player", b =>
                {
                    b.HasOne("Testx.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Testx.Models.Nationality", "Nationality")
                        .WithMany("Players")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Testx.Models.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Testx.Models.Nationality", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
